/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea.tema.pkg9;

import javafx.scene.paint.Color;
import javax.swing.JFrame;
import javax.swing.JRootPane;

/**
 *
 * @author Francisco
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        menuBar = new javax.swing.JPanel();
        findUser = new javax.swing.JLabel();
        listUsers = new javax.swing.JLabel();
        consultCash = new javax.swing.JLabel();
        addUser = new javax.swing.JLabel();
        transferCash = new javax.swing.JLabel();
        panels = new javax.swing.JPanel();
        findUserPanel = new javax.swing.JPanel();
        listUserPanel = new javax.swing.JPanel();
        transferPanel = new javax.swing.JPanel();
        consultcashAccount = new javax.swing.JPanel();
        initPanel = new javax.swing.JPanel();
        newUserPanel = new javax.swing.JPanel();
        remuneracion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioButton_cuentaAhorro = new javax.swing.JRadioButton();
        radioButton_CCorientePersonal = new javax.swing.JRadioButton();
        radioButton_CCorrienteEmpresa = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        enviarFormulario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        numeroCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaNacimiento = new javax.swing.JTextField();
        saldoInicial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        codigoCuenta = new javax.swing.JTextField();
        digitoControlCuenta = new javax.swing.JTextField();
        entidadCuenta = new javax.swing.JTextField();
        oficinaCuenta = new javax.swing.JTextField();
        ibanCuenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mantenimiento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        botonvalidarCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBar.setBackground(new java.awt.Color(51, 0, 153));
        menuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-50.png"))); // NOI18N
        findUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findUserMouseClicked(evt);
            }
        });
        menuBar.add(findUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 80, 80));

        listUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-clasificar-abajo-64.png"))); // NOI18N
        listUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersMouseClicked(evt);
            }
        });
        menuBar.add(listUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 80, 90));

        consultCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consultCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-money-64.png"))); // NOI18N
        consultCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultCashMouseClicked(evt);
            }
        });
        menuBar.add(consultCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 80, 80));

        addUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-50.png"))); // NOI18N
        addUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserMouseClicked(evt);
            }
        });
        menuBar.add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        transferCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transferCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-data-transfer-50.png"))); // NOI18N
        transferCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferCashMouseClicked(evt);
            }
        });
        menuBar.add(transferCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 80, 80));

        bg.add(menuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        panels.setLayout(new java.awt.CardLayout());

        findUserPanel.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout findUserPanelLayout = new javax.swing.GroupLayout(findUserPanel);
        findUserPanel.setLayout(findUserPanelLayout);
        findUserPanelLayout.setHorizontalGroup(
            findUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        findUserPanelLayout.setVerticalGroup(
            findUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        panels.add(findUserPanel, "card3");

        listUserPanel.setBackground(new java.awt.Color(255, 51, 51));
        listUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panels.add(listUserPanel, "card4");

        transferPanel.setBackground(new java.awt.Color(0, 255, 153));

        javax.swing.GroupLayout transferPanelLayout = new javax.swing.GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        panels.add(transferPanel, "card5");

        consultcashAccount.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout consultcashAccountLayout = new javax.swing.GroupLayout(consultcashAccount);
        consultcashAccount.setLayout(consultcashAccountLayout);
        consultcashAccountLayout.setHorizontalGroup(
            consultcashAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        consultcashAccountLayout.setVerticalGroup(
            consultcashAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        panels.add(consultcashAccount, "card6");

        javax.swing.GroupLayout initPanelLayout = new javax.swing.GroupLayout(initPanel);
        initPanel.setLayout(initPanelLayout);
        initPanelLayout.setHorizontalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
        );
        initPanelLayout.setVerticalGroup(
            initPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        panels.add(initPanel, "card7");

        newUserPanel.setBackground(new java.awt.Color(113, 213, 255));
        newUserPanel.setForeground(new java.awt.Color(255, 51, 51));
        newUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        remuneracion.setBackground(new java.awt.Color(113, 213, 255));
        remuneracion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        remuneracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        remuneracion.setToolTipText("");
        remuneracion.setAlignmentX(0.1F);
        remuneracion.setAlignmentY(0.1F);
        remuneracion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        remuneracion.setPreferredSize(new java.awt.Dimension(0, 2));
        newUserPanel.add(remuneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 50, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos");
        newUserPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 70, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha nacimiento ");
        newUserPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Saldo inicial");
        newUserPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, -1));

        radioButton_cuentaAhorro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioButton_cuentaAhorro.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_cuentaAhorro.setText("Cuenta de Ahorro");
        radioButton_cuentaAhorro.setOpaque(false);
        radioButton_cuentaAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_cuentaAhorroActionPerformed(evt);
            }
        });
        newUserPanel.add(radioButton_cuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 327, 160, 70));

        radioButton_CCorientePersonal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioButton_CCorientePersonal.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_CCorientePersonal.setText("Cuenta corriente perosnal");
        radioButton_CCorientePersonal.setOpaque(false);
        radioButton_CCorientePersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_CCorientePersonalActionPerformed(evt);
            }
        });
        newUserPanel.add(radioButton_CCorientePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 397, 220, 70));

        radioButton_CCorrienteEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        radioButton_CCorrienteEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        radioButton_CCorrienteEmpresa.setText("Cuenta corriente de empresa");
        radioButton_CCorrienteEmpresa.setOpaque(false);
        radioButton_CCorrienteEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_CCorrienteEmpresaActionPerformed(evt);
            }
        });
        newUserPanel.add(radioButton_CCorrienteEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 70));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nº Cuenta");
        newUserPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 90, 20));

        enviarFormulario.setBackground(new java.awt.Color(255, 255, 255));
        enviarFormulario.setForeground(new java.awt.Color(0, 51, 51));
        enviarFormulario.setText("Enviar");
        enviarFormulario.setPreferredSize(new java.awt.Dimension(0, 0));
        enviarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarFormularioActionPerformed(evt);
            }
        });
        newUserPanel.add(enviarFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 110, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("%");
        newUserPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 30, 20));

        nombre.setBackground(new java.awt.Color(113, 213, 255));
        nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, 30));

        apellidos.setBackground(new java.awt.Color(113, 213, 255));
        apellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        apellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 210, 30));

        numeroCuenta.setBackground(new java.awt.Color(113, 213, 255));
        numeroCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numeroCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(numeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 170, 30));

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("€");
        newUserPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 20, 30));

        fechaNacimiento.setBackground(new java.awt.Color(113, 213, 255));
        fechaNacimiento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fechaNacimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fechaNacimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        fechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoActionPerformed(evt);
            }
        });
        newUserPanel.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 210, 30));

        saldoInicial.setBackground(new java.awt.Color(113, 213, 255));
        saldoInicial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        saldoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        saldoInicial.setAlignmentX(0.1F);
        saldoInicial.setAlignmentY(0.1F);
        saldoInicial.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(saldoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 120, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Numero de cuenta");
        newUserPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, -1));

        codigoCuenta.setBackground(new java.awt.Color(113, 213, 255));
        codigoCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigoCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        codigoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        codigoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoCuentaActionPerformed(evt);
            }
        });
        newUserPanel.add(codigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 40, 30));

        digitoControlCuenta.setBackground(new java.awt.Color(113, 213, 255));
        digitoControlCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        digitoControlCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        digitoControlCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        digitoControlCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitoControlCuentaActionPerformed(evt);
            }
        });
        newUserPanel.add(digitoControlCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 50, 30));

        entidadCuenta.setBackground(new java.awt.Color(113, 213, 255));
        entidadCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        entidadCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entidadCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        entidadCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadCuentaActionPerformed(evt);
            }
        });
        newUserPanel.add(entidadCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 50, 30));

        oficinaCuenta.setBackground(new java.awt.Color(113, 213, 255));
        oficinaCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        oficinaCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oficinaCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(oficinaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 50, 30));

        ibanCuenta.setBackground(new java.awt.Color(113, 213, 255));
        ibanCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ibanCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ibanCuenta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(ibanCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Código");
        newUserPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("IBAN");
        newUserPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 40, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Entidad");
        newUserPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 70, 20));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Oficina");
        newUserPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 70, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("D.Control");
        newUserPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 90, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre  ");
        newUserPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Mantenimiento");
        newUserPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 20));

        mantenimiento.setBackground(new java.awt.Color(113, 213, 255));
        mantenimiento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mantenimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mantenimiento.setAlignmentX(0.1F);
        mantenimiento.setAlignmentY(0.1F);
        mantenimiento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(mantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 50, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("€");
        newUserPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 30, 20));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Descubierto");
        newUserPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 90, 30));

        descuento.setBackground(new java.awt.Color(113, 213, 255));
        descuento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descuento.setAlignmentX(0.1F);
        descuento.setAlignmentY(0.1F);
        descuento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        newUserPanel.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 50, 20));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("€");
        newUserPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 30, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Remuneración");
        newUserPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 110, 20));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("____________________________________________________________");
        newUserPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 480, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("____________________________________________________________");
        newUserPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 480, 20));

        botonvalidarCuenta.setBackground(new java.awt.Color(255, 255, 255));
        botonvalidarCuenta.setForeground(new java.awt.Color(0, 51, 51));
        botonvalidarCuenta.setText("Validar");
        botonvalidarCuenta.setPreferredSize(new java.awt.Dimension(0, 0));
        botonvalidarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvalidarCuentaActionPerformed(evt);
            }
        });
        newUserPanel.add(botonvalidarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 100, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALTA CLIENTE");
        newUserPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 90));

        panels.add(newUserPanel, "card2");

        bg.add(panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        getContentPane().add(bg);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserMouseClicked
        consultcashAccount.setVisible(false);
        findUserPanel.setVisible(false);
        listUserPanel.setVisible(false);
        newUserPanel.setVisible(true);
        transferPanel.setVisible(false);


    }//GEN-LAST:event_addUserMouseClicked

    private void findUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findUserMouseClicked
        consultcashAccount.setVisible(false);
        findUserPanel.setVisible(true);
        listUserPanel.setVisible(false);
        newUserPanel.setVisible(false);
        transferPanel.setVisible(false);


    }//GEN-LAST:event_findUserMouseClicked

    private void listUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersMouseClicked
        consultcashAccount.setVisible(false);
        findUserPanel.setVisible(false);
        listUserPanel.setVisible(true);
        newUserPanel.setVisible(false);
        transferPanel.setVisible(false);


    }//GEN-LAST:event_listUsersMouseClicked

    private void transferCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferCashMouseClicked
        consultcashAccount.setVisible(false);
        findUserPanel.setVisible(false);
        listUserPanel.setVisible(false);
        newUserPanel.setVisible(false);
        transferPanel.setVisible(true);


    }//GEN-LAST:event_transferCashMouseClicked

    private void consultCashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultCashMouseClicked
        consultcashAccount.setVisible(true);
        findUserPanel.setVisible(false);
        listUserPanel.setVisible(false);
        newUserPanel.setVisible(false);
        transferPanel.setVisible(false);


    }//GEN-LAST:event_consultCashMouseClicked

    private void radioButton_CCorientePersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_CCorientePersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_CCorientePersonalActionPerformed

    private void radioButton_cuentaAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_cuentaAhorroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_cuentaAhorroActionPerformed

    private void enviarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarFormularioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarFormularioActionPerformed

    private void fechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoActionPerformed

    private void codigoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoCuentaActionPerformed

    private void entidadCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entidadCuentaActionPerformed

    private void digitoControlCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitoControlCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitoControlCuentaActionPerformed

    private void radioButton_CCorrienteEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_CCorrienteEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_CCorrienteEmpresaActionPerformed

    private void botonvalidarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvalidarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonvalidarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame frame = new NewJFrame();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.addUser.setVisible(true);
                frame.consultcashAccount.setVisible(false);
                frame.findUserPanel.setVisible(false);
                frame.listUserPanel.setVisible(false);
                frame.newUserPanel.setVisible(true);
                frame.transferPanel.setVisible(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel addUser;
    private javax.swing.JTextField apellidos;
    private javax.swing.JPanel bg;
    private javax.swing.JButton botonvalidarCuenta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField codigoCuenta;
    private javax.swing.JLabel consultCash;
    private javax.swing.JPanel consultcashAccount;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField digitoControlCuenta;
    private javax.swing.JTextField entidadCuenta;
    private javax.swing.JButton enviarFormulario;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JLabel findUser;
    private javax.swing.JPanel findUserPanel;
    private javax.swing.JTextField ibanCuenta;
    public javax.swing.JPanel initPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel listUserPanel;
    private javax.swing.JLabel listUsers;
    private javax.swing.JTextField mantenimiento;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numeroCuenta;
    private javax.swing.JTextField oficinaCuenta;
    private javax.swing.JPanel panels;
    private javax.swing.JRadioButton radioButton_CCorientePersonal;
    private javax.swing.JRadioButton radioButton_CCorrienteEmpresa;
    private javax.swing.JRadioButton radioButton_cuentaAhorro;
    private javax.swing.JTextField remuneracion;
    private javax.swing.JTextField saldoInicial;
    private javax.swing.JLabel transferCash;
    private javax.swing.JPanel transferPanel;
    // End of variables declaration//GEN-END:variables
}
